#!/bin/sh

source $(dirname $0)/vars

# start docker on the mac
docker-machine start

# start db
docker run -d --name db \
  -v "/etc/postgresql" \
  -v "/var/log/postgresql" \
  -v "/var/lib/postgresql" \
  -p 5332:5432 \
  postgres:9.5.2
docker start db

# rebuild the image
cd ~/sonar/$APP/docker
docker build -t local/$APP .

# remove the old image
docker rm -f $APP

# start the new image
docker run -d --name $APP \
  -v ~/sonar/$APP:/home/app/webapp \
  -p 5000:80 -p 5443:443 \
  --link db:db \
  -e "SONAR_ENV=development" \
  -e "DATABASE_URL=$DATABASE_URL" \
  -e "SECRET_KEY_BASE=$SECRET_KEY_BASE" \
  -e "AIRSONAR_API_KEY=token LETMEIN" \
  --dns 8.8.8.8 --dns 8.8.4.4 \
  local/$APP

# bundle install
docker exec $APP bundle install

# fire up bash
docker exec -it $APP bash -l

# ./thin
